# 1.创建数组对象

## 使用array 函数创建数组对象

In [ ]:
import numpy as np

In [2]:
# 列表
data1 = [1,3,5,7]
w1 = np.array(data1)
print("w1:",w1)

# 元组
data2 = (2,4,6,8)
w2 = np.array(data2)
print("w2:",w2)

# 多维数组
data3 = [[1,2,3,4],[5,6,7,8]]
w3 = np.array(data3)
print("w3:",w3)

w1: [1 3 5 7]
w2: [2 4 6 8]
w3: [[1 2 3 4]
 [5 6 7 8]]


## 专门创建数组的函数
1) arange 函数
2) linspace 函数
3) logspace 函数
4) zeros 函数
5) ones 函数
6) diag 函数

In [4]:
# 1.arange函数
warray1 = np.arange(10)
print(warray1)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
# 2.linspace 函数
warray2 = np.linspace(0,1,5)
print(warray2)

[0.   0.25 0.5  0.75 1.  ]


In [8]:
# 3.logspace 函数
warray3 = np.logspace(0,1,5)
# 生成 1~10 的具有5个元素的等比数列 (默认参数为1e）
print(warray3)

[ 1.          1.77827941  3.16227766  5.62341325 10.        ]


In [10]:
# 4.zeors 函数
# zeros 函数可以创建指定传毒或形状的全0数组
print(np.zeros(4))
print(np.zeros([3,3]))

[0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
# 5.ones 函数
# ones 函数可以穿甲指定长度或形状的全1数组
print(np.ones(4))
print(np.ones([3,3]))

[1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [13]:
# 6.diag 函数
# diag函数可以创建对角矩阵，即对角线元素为0或指定值，其他元素为0
print(np.diag([1,2,3,4]))

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


# 2.ndarray 对象属性和数据转换
NumPy 创建的 ndarray 对象属性主要有 shape、size 等属性

In [15]:
# 查看数组的属性
warray = np.array([[1,2,3],[4,5,6]])
print("秩为：",warray.ndim)
print("形状为：",warray.shape)
print("元素个数为：",warray.size)

秩为： 2
形状为： (2, 3)
元素个数为： 6


# 3.生成随机数

In [17]:
arr = np.random.randint(100,200,(2,4))
print(arr)

[[138 172 144 174]
 [190 106 110 105]]


# 4.数组变换

## 数组重塑

In [20]:
# 改变数组维度
arr1 = np.arange(8)
print(arr1)
arr2 = arr1.reshape(4,2)
print(arr2)

[0 1 2 3 4 5 6 7]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


## 数组合并

In [21]:
# 横向合并(hstack) (纵向vstack）
arr1 = np.arange(6).reshape(3,2)
arr2 = arr1*2
arr3 = np.hstack((arr1,arr2))
print(arr3)

[[ 0  1  0  2]
 [ 2  3  4  6]
 [ 4  5  8 10]]


## 数组分割
与数组合并相反，有横向、纵向和指定方向的分割

In [24]:
arr = np.arange(16).reshape(4,4)
print('横向分割：\n',np.hsplit(arr,2))
print('纵向分割：\n',np.vsplit(arr,2))

横向分割：
 [array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
纵向分割：
 [array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


## 数组装置和轴对换

In [26]:
arr = np.arange(6).reshape(3,2)
print('矩阵：\n',arr)
print('转置矩阵\n',arr.transpose((1,0)))

矩阵：
 [[0 1]
 [2 3]
 [4 5]]
转置矩阵
 [[0 2 4]
 [1 3 5]]
