数组的运算支持向量化运算，将本来需要在 Python级别进行的运算放到 C语言的运算中，会明显地提高程序地运算速度

# 1.数组和标量之间的运算

In [1]:
import numpy as np

In [2]:
# 数组元素的追加
a = [1,2,3]
b = []
for i in a:
    b.append(i*i)
print('b数组：',b)
wy = np.array([1,2,3])
c = wy * 2
print('c数组：',c)

b数组： [1, 4, 9]
c数组： [2 4 6]


# 2.ufunc函数

## 常用的 ufunc 函数运算
常用的 ufunc 函数运算有四则运算、比较运算和逻辑运算

In [3]:
# 数组的四则运算
x = np.array([1,2,3])
y = np.array([4,5,6])
print('数组相加结果∶',x+y)
print('数组相减结果∶',x-y)
print('数组相乘结果∶',x*y)
print('数组幂运算结果∶',x**y)

数组相加结果∶ [5 7 9]
数组相减结果∶ [-3 -3 -3]
数组相乘结果∶ [ 4 10 18]
数组幂运算结果∶ [  1  32 729]


## ufunc 函数的广播机制
广播（broadcasting）是指不同形状的数组之间执行算术运算的方式。广播机制需要遵循4个原则∶
（1）让所有输入数组都向其中shape最长的数组看齐，shape中不足的部分都通过在前面加1补齐。
（2）输出数组的shape是输入数组shape的各个轴上的最大值。
（3）如果输入数组的某个轴和输出数组的对应轴的长度相同或者其长度为1时，这个数组能够用来计算，否则出错。
（4）当输入数组的某个轴的长度为1时，沿着此轴运算时都用此轴上的第一组值。


In [4]:
arr1 = np.array([[0,0,0],[1,1,1],[2,2,2]])
arr2 = np.array([1,2,3])
print('arr1:\n',arr1)
print('arr2:\n',arr2)
print('arr1+arr2:\n',arr1+arr2)

arr1:
 [[0 0 0]
 [1 1 1]
 [2 2 2]]
arr2:
 [1 2 3]
arr1+arr2:
 [[1 2 3]
 [2 3 4]
 [3 4 5]]


# 3.条件逻辑运算
在NumPy中可以使用基本的逻辑运算实现数组的条件运算。