数组的运算支持向量化运算，将本来需要在 Python级别进行的运算放到 C语言的运算中，会明显地提高程序地运算速度

# 1.数组和标量之间的运算

In [2]:
import numpy as np

In [2]:
# 数组元素的追加
a = [1,2,3]
b = []
for i in a:
    b.append(i*i)
print('b数组：',b)
wy = np.array([1,2,3])
c = wy * 2
print('c数组：',c)

b数组： [1, 4, 9]
c数组： [2 4 6]


# 2.ufunc函数

## 常用的 ufunc 函数运算
常用的 ufunc 函数运算有四则运算、比较运算和逻辑运算

In [3]:
# 数组的四则运算
x = np.array([1,2,3])
y = np.array([4,5,6])
print('数组相加结果∶',x+y)
print('数组相减结果∶',x-y)
print('数组相乘结果∶',x*y)
print('数组幂运算结果∶',x**y)

数组相加结果∶ [5 7 9]
数组相减结果∶ [-3 -3 -3]
数组相乘结果∶ [ 4 10 18]
数组幂运算结果∶ [  1  32 729]


## ufunc 函数的广播机制
广播（broadcasting）是指不同形状的数组之间执行算术运算的方式。广播机制需要遵循4个原则∶
（1）让所有输入数组都向其中shape最长的数组看齐，shape中不足的部分都通过在前面加1补齐。
（2）输出数组的shape是输入数组shape的各个轴上的最大值。
（3）如果输入数组的某个轴和输出数组的对应轴的长度相同或者其长度为1时，这个数组能够用来计算，否则出错。
（4）当输入数组的某个轴的长度为1时，沿着此轴运算时都用此轴上的第一组值。


In [4]:
arr1 = np.array([[0,0,0],[1,1,1],[2,2,2]])
arr2 = np.array([1,2,3])
print('arr1:\n',arr1)
print('arr2:\n',arr2)
print('arr1+arr2:\n',arr1+arr2)

arr1:
 [[0 0 0]
 [1 1 1]
 [2 2 2]]
arr2:
 [1 2 3]
arr1+arr2:
 [[1 2 3]
 [2 3 4]
 [3 4 5]]


# 3.条件逻辑运算
在NumPy中可以使用基本的逻辑运算实现数组的条件运算。

In [7]:
# 如果满足条件 输出 x：不满足则输出 y

arr1 = np.array([1,3,5,7])
arr2 = np.array([2,4,6,8])
cond = np.array([True,False,True,False])
result = np.where(cond,arr1,arr2)
print(result)

[1 4 5 8]


# 4.数组读/写

##  读/写二进制文件
NumPy提供了多种文件操作函数存取数组内容。文件存取的格式分为两类∶二进制和文本。二进制格式的文件又分为NumPy专用的格式化二进制类型和无格式类型。NumPy中读/写二进制文件的方法有以下两种。
（1）NumPy.load（"文件名.npy"）∶从二进制的文件中读取数据。
（2）NumPy.save（"文件名\[.npy]"，arr）∶以二进制的格式保存数据。
它们会自动处理元素类型和shape等信息，使用它们读/写数组就非常方便。但是np.save 输出的文件很难用其他语言编写的程序读入。

In [10]:
# 数组的读/写
a = np.arange(1,13).reshape(3,4)
print(a)
np.save('arr.npy',a)
c = np.load('arr.npy')
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## 读/写文本文件
NumPy 中读/写文本文件的主要方法有以下几种。
（1）NumPy.loadtxt("./tmp/arr.txt",delimiter=",")∶把文件加载到一个二维数组中。
（2）NumPy.savetxt("../tmp/arr.txt",arr，fmt="%d",delimiter=",")∶将数组写到某种分隔符隔开的文本文件中。
（3）NumPy.genfromtxt("./tmp/arr.txt",delimiter=",")∶结构化数组和缺失数据。


In [11]:
a = np.arange(0,12,0.5).reshape(4,-1)
np.savetxt("a1-out.txt",a)
# 默认按照 '%.18e' 格式保存数值
np.loadtxt("a1-out.txt")
np.savetxt('a2-out.txt',a,fmt='%d',delimiter= ",")
# 改为保存为整数，以逗号分隔

np.loadtxt('a2-out.txt',delimiter=',')
# 读入的时候也需要指定逗号分隔

array([[ 0.,  0.,  1.,  1.,  2.,  2.],
       [ 3.,  3.,  4.,  4.,  5.,  5.],
       [ 6.,  6.,  7.,  7.,  8.,  8.],
       [ 9.,  9., 10., 10., 11., 11.]])

## 读取 CSV 文件
