# 3.常用的统计函数

In [1]:
import numpy as np

In [2]:
arr = np.arange(20).reshape(4,5)
print('创建的数组：\n',arr)

print('数组的和：',np.sum(arr))

print('数组纵轴的和：',np.sum(arr,axis= 0))

print('数组横轴的和：',np.sum(arr,axis=1))

print('数组的均值：',np.mean(arr))

print('数组横轴的均值：',np.mean(arr,axis=1))

print('数组的标准差：',np.std(arr))

print('数组横轴的标准差：',np.std(arr,axis=1))

创建的数组：
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
数组的和： 190
数组纵轴的和： [30 34 38 42 46]
数组横轴的和： [10 35 60 85]
数组的均值： 9.5
数组横轴的均值： [ 2.  7. 12. 17.]
数组的标准差： 5.766281297335398
数组横轴的标准差： [1.41421356 1.41421356 1.41421356 1.41421356]
