# 1.一维数组的索引

In [2]:
import numpy as np


In [3]:
arr = np.arange(10)
print(arr)
print(arr[2])
print(arr[-1])
print(arr[1:4])

[0 1 2 3 4 5 6 7 8 9]
2
9
[1 2 3]


# 2.多维数组的索引

In [4]:
arr = np.arange(12).reshape(3,4)
print(arr)
# 索引第0行中第1列到第2列的元素
print(arr[0,1:3])
# 索引第2列元素
print(arr[:2])
# 第0行第0列元素
print(arr[:1,:1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[1 2]
[[0 1 2 3]
 [4 5 6 7]]
[[0]]
